Add webhook for all CRs
openstack-k8s-operators/test-operator pull request #160
Opened 2024-08-05 14:20 UTC by kstrenkova

There is a need to add webhooks to all CRs like it was done for Tempest CR. In this patch webhooks for Tobiko, HorizonTest and AnsibleTest are added. There is an effort to make the webhook as generic as possible to minimize the duplicate code.

2024-08-09 08:00 UTC, lpiwowar commented
Can we split this please into two PRs, please?
* One for addition of the webhooks
* Second for merging of the workflows

2024-08-09 08:00 UTC, lpiwowar requested changes
Can we split this please into two PRs, please?
* One for addition of the webhooks
* Second for merging of the workflows

2024-08-16 13:02 UTC, lpiwowar reviewed
Looks good to me there are just two tasks left one for @kstrenkova and second for @lpiwowar (I'm going to take a look on this on Monday). Otherwise the PR looks good to me. These are just small things to polish:).

2024-08-19 15:02 UTC, kstrenkova commented on hack/configure_local_webhook.sh
> +fi
Ack, I changed the patch accordingly.

2024-08-20 13:32 UTC, merged