[docs] Change namespace to openstack-test-operator
openstack-k8s-operators/test-operator pull request #265
Opened 2024-12-12 14:18 UTC by lpiwowar

Recently we changed the test-operator from cluster scoped to namespace
scoped operator. This patch ensures that we reflect this change in the
test-operator documentation.

2024-12-19 14:53 UTC, lpiwowar commented
/test all

2025-01-14 16:07 UTC, kstrenkova requested changes

2025-01-14 16:07 UTC, kstrenkova commented on docs/source/guide.rst
> +   oc get installplans -n openstack-test-operator | grep "test-operator"
When I test the patch, I didn't find any installplans in `openstack-test-operator` namespace. Don't know why that is, maybe it was fault in my testing, but I still wanted to ask about this.

2025-01-16 12:42 UTC, lpiwowar commented
Thank you @kstrenkova for the review!:) I'm closing the PR because we agreed not to switch the test-operator to a namespace scoped operator. The discussion can be found here -> https://github.com/openstack-k8s-operators/test-operator/pull/264

2025-01-16 12:42 UTC, closed without merging