Remove unnecessary rights
openstack-k8s-operators/test-operator pull request #267
Opened 2024-12-13 14:33 UTC by lpiwowar

In this PR [1] we dropped the usage of the Jobs by the test-operator.
This allows us to drop the rights for:

 - ServiceAccount managing & creation
 - Role managing & creation
 - RoleBinding managing & creation

These rights were only needed because Jobs were required to be spawned
with an extra ServiceAccount that would have elevated privileges in case
the test pods need to run with privileged SecurityContext.

[1] https://github.com/openstack-k8s-operators/test-operator/pull/266

Depends-On: https://github.com/openstack-k8s-operators/test-operator/pull/266

2024-12-13 14:34 UTC, lpiwowar commented
recheck

2025-01-17 09:23 UTC, lpiwowar commented
This PR will be rebased and ready for a review once this PR gets merged -> https://github.com/openstack-k8s-operators/test-operator/pull/266

2025-01-28 12:13 UTC, kstrenkova requested changes
Without the requested change, I was not able to run the change properly. Other than that, the patch seems to be working.

2025-01-28 12:13 UTC, kstrenkova commented on controllers/tempest_controller.go
>  // +kubebuilder:rbac:groups=test.openstack.org,resources=tempests/finalizers,verbs=update;patch
I don't know how to add this comment on line 35, but the `common_rbac` definition should be also deleted for this patch to work.

2025-01-28 12:30 UTC, lpiwowar reviewed
Thank you:)

2025-02-26 12:21 UTC, lpiwowar commented
/test test-operator-build-deploy

2025-02-26 14:28 UTC, arxcruz commented
/lgtm

2025-02-26 14:32 UTC, merged